Unidata/thredds-docker

README.md
bit of verbage for building container
=> building the container

README.md, docker-compose.yml
=> docker-compose.yml

Dockerfile
=> clean up Dockerfile

README.md, docker-compose.yml
=> unidata/thredds-docker --> unidata/tds

README.md, docker-compose.yml
=> tomcat log files

README.md
since we still need to hammer out some stuff
=> under construction notice

Dockerfile.tdm
=> cleaning up tomcat user

Dockerfile, files/javaopts.sh
closes #49 
`javaopts.sh` gets redone in #48, but this PR can't hurt
=> JAVA_PREFS_SYSTEM_ROOT according to @gajowi

README.md
Closes #43 to address issue mentioned @kwilcox is #34
=> Explanation of docker-compose

README.md, docker-compose.yml
=> correcting tdm image reference

README.md
=> fixing broken links

README.md
=> cleaning up tomcat related instructions

Dockerfile
=> Reasserting ownership/permissions from parent container

README.md
=> ssl instructions

.travis.yml
=> building docker image with --no-cache

README.md
=> running w/ gosu should render this verbage moot

README.md
=> Java Configuration Options

README.md
=> 5.0-SNAPSHOT info

README.md
=> Removing "UNDER CONSTRUCTION" notice.

README.md
=> clarifying usage of TDM

.travis.yml
=> More Efficient Travis Configuration

Dockerfile
Fixing error introduced in af3482d
Closes #108. Related to #107.
=> Fixing Error Introduced in af3482d

.travis/test.sh
=> Less Stringent Test

.travis.yml
=> ping actual catalog

README.md
closes #136. @isuftin tackling low-hanging fruit first. OK with you? You are the author, BTW :-)
=> docker-machine info

LICENSE.txt
=> update to 2017

Dockerfile, README.md, compose.env, docker-compose.yml, files/javaopts.sh
closes #137 and #149. Probably going to have to iterate a few times before getting this PR right.
=> parameterizing docker-compose w/ environment variables

Dockerfile, README.md, docker-compose.yml
=> trailing white space cleanup

docker-compose.yml
=> docker-compose version 3

README.md, compose.env
=> more tdm env vars

.travis/test.sh
=> travis 5.0-SNAPSHOT fix

Dockerfile
=> fix hdf url

files/javaopts.sh
=> jna temp dir

Dockerfile
=> docker healthcheck

CHANGELOG.md, README.md, README_SWARM.md, docker-compose-swarm.yml
=> docker swarm

README.md
Signed-off-by: Sven Dowideit <Sven.Dowideit@csiro.au>
=> Note that remote management is enabled, and link to docs

Dockerfile, README.md, files/threddsConfig.xml
=> more ncsos

CHANGELOG.md, Dockerfile, README.md, docker-compose-swarm.yml, files/threddsConfig.xml
=> 5.0 snapshot

Dockerfile, README.md, compose.env
=> unidata/tomcat-docker:8.5

Dockerfile
closes #198. Thanks @DennisHeimbigner .
=> Updating netCDF

README.md
=> support section

docker-compose-swarm.yml, docker-compose.yml
If this needs to be against something other than master branch, please let me know.
=> Change container version to latest.

CHANGELOG.md, docker-compose-swarm.yml, docker-compose.yml
cleaned up version of #218 by @isuftin
=> Updated Docker Compose versions to 3.7

README.md
=> clarifying TDM a bit

.org/readme.org, README.md
=> readme revamp

Dockerfile
=> zlib update

.github/testScripts/test.sh, .github/workflows/docker-image.yml
Implementing auto-build and simple test of the TDS. See link below for recent successful workflow run on push:
https://github.com/robertej09/thredds-docker/actions
=> Implement Github Actions workflow
